spring.application.name=dental-clinic
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-falling-sun-b5lzfii7-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_6qrPXlFsVa3L}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

spring.flyway.enabled=false
springdoc.swagger-ui.path=/swagger-ui.html

spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false